name: Release

# 关键修改：添加 workflow_dispatch 支持手动触发
on:
  push:
    tags:
      - 'v*.*.*'  # 原有：推送标签自动触发
  workflow_dispatch:  # 新增：支持网页手动触发（无参数）
    # （可选）若需要手动触发时指定版本/标签，可添加输入参数，示例：
    inputs:
      tag_name:
        description: '指定要发布的标签（如 v1.0.0，需提前存在）'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # （若添加了tag_name参数，需指定 checkout 对应标签）
          ref: ${{ github.event.inputs.tag_name || github.ref }}  # 优先用手动输入的标签，否则用触发时的ref（如推送的标签）
      - name: Fetch tags
        run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Release with Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
